- name: printing the command
  hosts: frontend
  tasks:
  - name: ping the server
    ansible.builtin.ping:
    register: ping output
  - name: print the message
    ansible.builtin.debug:
      msg: "{{ ping output }}"
