- name: printing the command
  hosts: frontend
  tasks:
  - name: ping the server
    ansible.builtin.ping:
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "ping the server"
