- name: printing the command
  hosts: frontend
  tasks:
  - name: ping the server
    ansible.builtin.ping:
    register: command_result
  - name: print the message
    ansible.builtin.debug:
      msg: {{ command_result }}
