- name: nginx install and run
  hosts: frontend
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
    register: nginx_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ nginx_output }}"

  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: stop
      enabled: yes
    register: service_output

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ service_output }}"
