- name: nginx install and run
  hosts: frontend
  connection: local
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: status nginx
    ansible.builtin.service:
      name: nginx
      state: status