- name: variables from command line
  hosts: local
  connection: local
  tasks:
  - name: print course info
    ansible.builtin.debug:
      msg: "Hello I am learning {{ IDEA }}, Duration: {{ DURATION }}, Trainer is: {{ TRAINER }}"