- name: Data Types and its work
  hosts: local
  connection: local
  vars:
    DURATION: 120
    TRAINER: Sivakumar
    IS_LIVE: true
    COURSE:
      - Linux
      - shell
      - Ansible
    SCRIPTING:
      CI: Github
  tasks:
  - name: checking the datatypes
    ansible.builtin.debug:
      msg: The Course is {{ COURSE }}, Duration is {{ DURATION }} is live:? {{ IS_LIVE }} and trainer os {{ TRAINER }}
          about scripting {{ SCRIPTING }}
