- name: conditions in Ansible
  hosts: local
  connection: local
  vars_prompt:
  - name: NUMBER
    prompt: enter the number
    
  tasks:
  - name: the given number is less than 100
    ansible.builtin.debug:
      msg: "the given number {{ NUMBER }} is less than 100"
    when: NUMBER <= 100
