- name: Configuring the variables
  hosts: local
  connection: local
  become: yes
  vars:
    COURSE: DevOps
    DURATION: 2HR
    Trainer: Balayya
  tasks:
  - name: Checking play level vars
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }}, Duaration: {{ DURATION }} and the Trainer is {{ Trainer }}"

  - name: Checking task level vars
    vars:
    COURSE: Python
    DURATION: 2HR
    Trainer: Chiru
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }}, Duaration: {{ DURATION }} and the Trainer is {{ Trainer }}"
  