- name: Checking all the modules
  hosts: local
  connection: local
  tasks:
  - name: Pinging the hosts
    ansible.builtin.ping:

  - name: printing the course details
    ansible.builtin.debug:
      msg: "The course details are "