- name: Checking all the modules
  hosts: local
  connection: local
  tasks:
  - name: Pinging the hosts
    ansible.builtin.ping:

  - name: printing the course details
    vars:
      COURSE: Ansible
      DURATION: 1 HR
    ansible.builtin.debug:
      msg: "The course details are {{ COURSE }} and the duration is {{ DURATION }}"

  - name: Installing the nginx server
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Starting the nginx server
    ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes